=== ptrckgllghr/misc/xml/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
		<xsd:complexType name="personType">
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" />
				<xsd:element name="age" type="xsd:int" />
				<xsd:element name="city" type="xsd:string" />
				<xsd:element name="phone" type="xsd:string" maxOccurs="2" />
				<xsd:element name="email" type="xsd:string" minOccurs="0" />
				<xsd:choice>
					<xsd:element name="citizen" />
					<xsd:element name="alien" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:element name="person" type="personType" />
</xsd:schema>

=== ptrckgllghr/misc/xml/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:noNamespaceSchemaLocation="person.xsd">

	<name>Frank Days</name>
	<age>29</age>
	<city>Las Vegas</city>
	<phone>123-234-4321</phone>
	<phone>123-890-8764</phone>
	<email>days@gmail.com</email>
	<citizen />
</person>
